apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-cert
  namespace: portfolio
spec:
  dnsNames:
    - de-marauder.me
  secretName: portfolio-server-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
