apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: monitoring
spec:
  dnsNames:
    - monitor.de-marauder.me
  secretName: prometheus-server-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
