apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sock-shop-cert
  namespace: sock-shop
spec:
  dnsNames:
    - sock.de-marauder.me
  secretName: sock-shop-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
